name: bioinfo
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - curl=7.83.1=h2283fc2_0
  - expat=2.7.3=h3385a95_0
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=hf484d3e_1000
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcurl=7.83.1=h2283fc2_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h516909a_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncbi-ngs-sdk=2.11.2=hff44eed_0
  - ncurses=6.5=h7934f7d_0
  - openjdk=11.0.1=h516909a_1016
  - openssl=3.0.18=hd6dcaed_0
  - ossuuid=1.6.2=hf484d3e_1000
  - perl=5.26.2=h36c2ea0_1008
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-parent=0.236=pl526_1
  - perl-uri=1.76=pl526_0
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xsloader=0.24=pl526_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sra-tools=2.11.0=pl5262h314213e_1
  - tk=8.6.15=h54e0aa7_0
  - trimmomatic=0.40=hdfd78af_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
prefix: /home/codespace/miniconda/envs/bioinfo
